### ISSUE TITLE
谢谢，亲测可用，i5-8250U 可用播放1080p h265

### ISSUE THREAD

**Issue by 7956968** [huskar-t/h265#3]
略卡顿,但不影响体验

**Comment by huskar-t** [comment]
解析线程数可以适当调整（不一定越大越好），时刻注意cpu温度。如果出现帧乱序就调大一点缓存队列长度

**Comment by 7956968** [comment]
我就一个解码线程，实时视频我感觉不适合分段解码

**Comment by 7956968** [comment]
而且我做了一下改进，websocket接收数据指定为arrayBuf，就可以不用stringToBinary了，不知道怎么发给你。
