### ISSUE TITLE
请问为什么会需要rtsp的地址啊

### ISSUE THREAD

**Issue by songyunao05** [huskar-t/h265#8]
请问大佬，为什么会需要rtsp的地址啊，后端websocket直接推的h265的流，能不能适用呢？

**Comment by huskar-t** [comment]
@songyunao05 不需要rtsp，这个库只是用来播放h265的，只要 websocket 按照格式推流就行

**Comment by songyunao05** [comment]
@huskar-t 但是会有检测啊，哪个rtsp接收的参数，应该传什么呢，为空的话会反馈视频地址错误呀

**Comment by huskar-t** [comment]
@songyunao05 
每个包为二进制流内容为 nalutype + nalu

```
 this.ws.onmessage = function (evt) {
            that.tps += 1
            let nType = evt.data.charCodeAt(0)
            if (nType === 32) {
                that.workerIndex += 1
                that.workerIndex %= that.options.worker
            }
            that.events.emit(EventsConfig.DateIn, {
                data: evt.data,
                index: that.workerIndex,
                pts : that.tps
            })
        };
```

这个项目只有前端，给你的后台发送ws时带的rtsp地址你可以不关心，直接推流就可以，或者修改一下代码把这部分给去掉

**Comment by songyunao05** [comment]
@huskar-t 意思就是哪个地址可以不需要是吧，我是怕解转码哪里会不会有用到，因为哪块的东西不懂，感谢

**Comment by huskar-t** [comment]
@songyunao05 是不需要的，这个项目是对接我的后台的，我的后台是取rtsp码流的所以需要传过来一个rtsp地址

**Comment by songyunao05** [comment]
@huskar-t 请问项目如何启动，我用代理起动起来是空白页面

**Comment by huskar-t** [comment]
@songyunao05 可以直接使用 dist 文件夹下的成品

**Comment by songyunao05** [comment]
项目是一启动就会去播放吗？因为抱错所以白页面，libffmpeg请求404

**Comment by songyunao05** [comment]
@huskar-t 项目是一启动就会去播放吗？因为抱错所以白页面，libffmpeg请求404

**Comment by huskar-t** [comment]
@songyunao05  libffmpeg 没法直接使用，需要把帧的类型放到ws数据的第一位，建议检查ws是否连通，数据是否正确

**Comment by songyunao05** [comment]
@huskar-t dist下面走的bundle，没法调试，我尝试自建html，但是会导致
![1628752057(1)](https://user-images.githubusercontent.com/50287503/129153080-c4df78ed-3426-4738-a6d5-873289a4575d.png)
![image](https://user-images.githubusercontent.com/50287503/129151426-bdca3161-6065-4791-bbbc-a7aeb4c7b975.png)
是否有成功示例或者建议指导呢，感谢大佬

**Comment by huskar-t** [comment]
@songyunao05 需要webpack打包后使用 ，建议直接使用webstorm进行调试
[webpack文档](https://webpack.docschina.org/concepts/)

**Comment by songyunao05** [comment]
@huskar-t 打包只是会输出可以部署的文件，现在想本地调试，就不会使用打包把文件集中啊，是各个文件里面去起debugger看下流程呢

**Comment by huskar-t** [comment]
@songyunao05 直接用webstorm吧。打包可以输出map文件支持调试
